version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: hotel-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hotel_reservations

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hotel-backend
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - JWT_SECRET=hotel-secret-key-docker-2025
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    volumes:
      - ./frontend:/app

volumes:
  mongodb_data: